path_classifiers:
    test:
      - "tests/*"

extraction:
    cpp:
        prepare:
            packages: 
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-gnutls-dev
            - libkrb5-dev
            - libhttp-parser-dev
            - libgit2-dev
            - libcrypto++-dev
            - libqt5qml5
            - libqt5quick5
            - libqt5svg5-dev
            - libqt5webkit5-dev
            - libsqlite3-dev
            - qml-module-qtlocation
            - qml-module-qtpositioning
            - qml-module-qtquick2
            - qt5-default
            - qt5-qmake
            - qtchooser
            - qtconnectivity5-dev
            - qtdeclarative5-dev
            - qtdeclarative5-private-dev
            - qtlocation5-dev
            - qtpositioning5-dev
            - qtscript5-dev
            - qttools5-dev
            - qttools5-dev-tools
            - qtquickcontrols2-5-dev
        after_prepare:
            - export INSTALL_ROOT=/opt/out
            - export PKG_CONFIG_PATH=$INSTALL_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH
            - bash -x ./scripts/build-libdivecomputer.sh

queries:
    - exclude: "cpp/short-global-name"
