

matrix:
  include:
    - env: SUBSURFACE_PLATFORM='ios'
      os: osx
      osx_image: xcode9.3
      language: c++

    - env: SUBSURFACE_PLATFORM="android"
      # Currently hard coded to arm
      os: linux
      language: c++
      filter_secrets: false
      services:
          - docker

before_install:
    - source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/before_install.sh

script:
    - source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/travisbuild.sh

after_success:
    - source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/after_success.sh

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/
