name: Ubuntu 19.10 / Qt 5.12
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildInContainer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: run build
      env:
        SSRF_USER_EMAIL: ssrftest-u19@hohndel.org
        SSRF_USER_PASSWORD: ${{ secrets.cloudu19 }}
      run: |
        cd ..
        bash -x subsurface/.github/workflows/scripts/ubuntu-in-container-build.sh

