name: Linux Qt 5.12 Ubuntu 19.10
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildInContainer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: run build
      run: |
        cd ..
        bash -x subsurface/.github/workflows/scripts/ubuntu-in-container-build.sh

