name: Linux Qt 5.12 Docker Image CI

on:
  push:
    paths:
    - scripts/docker/trusty-qt512/Dockerfile
    - .github/workflows/linux-docker*

jobs:
  trusty-qt512:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ '1.0' }}    # 'official' images should have a dot-zero version

    steps:
    - uses: actions/checkout@v1

    - name: Get our pre-reqs
      run: |
        cd scripts/docker/trusty-qt512
        bash getpackages.sh

    - name: set env
      run: |
        v=${{ env.VERSION }}
        echo "::set-env name=NAME::subsurface/trusty-qt512:${v}"

    - name: Build and Publish Linux Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:       ${{ env.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'Dockerfile'
        workdir:    './scripts/docker/trusty-qt512/'
